### ISSUE TITLE
ABAP2EXCEL trying to activate 

### ISSUE THREAD

**Issue by dorenthe** [ivanfemia/abap2xlsx#3]
Hi guys,
trying to activate the abap2xlsx project but:

![1_Problem](https://user-images.githubusercontent.com/62599182/77464602-b644a580-6e07-11ea-912a-fac11b3a9eef.png)
![1a Problem](https://user-images.githubusercontent.com/62599182/77464605-b6dd3c00-6e07-11ea-8713-303f6409241a.png)
![2020-03-24 19_42_52-Runtime Error - Description of Exception](https://user-images.githubusercontent.com/62599182/77464607-b775d280-6e07-11ea-957e-ff1f95b477d2.png)

**Comment by rrajgor** [comment]
Hi, you need to activate ZEXCEL_S_DRAWINGS structure and than ZEXCEL_T_DRAWINGS TableType, and finally activate ZCL_EXCEL_DRAWINGS class, also activate ZEXCEL_S_WORKSHEET_HEAD_FOOT structure

**Comment by dorenthe** [comment]
Hi and thanks,
could you provide me the structure of those types please:

  class-data WT_OBJECTS type TT_ALV_TYPES .
  data WT_SORT_VALUES type TT_SORT_VALUES .
  data WT_SUBTOTAL_ROWS type TT_SUBTOTAL_ROWS .
  data WT_STYLES type TT_STYLES .

thank you

**Comment by ivanfemia** [comment]
Dear abap2xlsx friend the repository has been moved to the sapmentors github account https://github.com/sapmentors/abap2xlsx
