### ISSUE TITLE
cl_abap_typedescr=>typekind_int8 doesn't exist in ECP

### ISSUE THREAD

**Issue by ccphantom** [ivanfemia/abap2xlsx#4]
![ABAP2XLSX issue](https://user-images.githubusercontent.com/22863868/86251589-add2d800-bb77-11ea-84e6-7f994d764afe.png)
in line 68 of the method "SET_CELL" in class "ZCL_EXCEL_WORKSHEET", class cl_abap_typedescr doesn't has the attribute "typekind_int8" in SAP ECP system, it will cause a dump.

**Comment by ivanfemia** [comment]
Dear abap2xlsx friend the repository has been moved to the sapmentors github account https://github.com/sapmentors/abap2xlsx
