### ISSUE TITLE
Error in ZDEMO_EXCEL29

### ISSUE THREAD

**Issue by PENGFARLEY** [ivanfemia/abap2xlsx#6]
Dear Team,,

I try to run the demo program: ZDEMO_EXCEL29 with a Macro-enabled Workbook.
There is an ABAP Dump in line 64:   lv_file = lo_excel_writer->write_file( lo_excel ).
when I debug I found: the first row the table LO_WORKSHEET->SHEET_CONTENT, the cell_row value is 0.

**Comment by ivanfemia** [comment]
Dear abap2xlsx friend the repository has been moved to the sapmentors github account https://github.com/sapmentors/abap2xlsx
